export const API_BASE = '/api';

export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  WORKSPACE: '/workspace',
  PROJECTS: '/projects',
  PROJECT_DETAIL: '/projects/:id',
  TASK_CREATE: '/projects/:id/tasks/new',
  TASK_MAPPING: '/projects/:id/tasks/:taskId/mapping',
  TASK_PROGRESS: '/projects/:id/tasks/:taskId/progress',
  TASK_CONTENT: '/projects/:id/tasks/:taskId/content',
  TASK_CLEANING: '/projects/:id/tasks/:taskId/comments/cleaning',
  TASK_INSIGHTS: '/projects/:id/tasks/:taskId/insights',
  TASK_HIGH_VALUE: '/projects/:id/tasks/:taskId/high-value',
  TASK_DEMAND_MAP: '/projects/:id/tasks/:taskId/demand-map',
  TASK_BARRIER_MAP: '/projects/:id/tasks/:taskId/barrier-map',
  TASK_ATTRIBUTION: '/projects/:id/tasks/:taskId/attribution',
  TASK_STRATEGY: '/projects/:id/tasks/:taskId/strategy',
  TASK_PRODUCTION_DOUYIN: '/projects/:id/tasks/:taskId/production/douyin',
  TASK_PRODUCTION_XHS: '/projects/:id/tasks/:taskId/production/xiaohongshu',
  TASK_COMMENT_OPS: '/projects/:id/tasks/:taskId/comment-ops',
  TASK_AD_FIT: '/projects/:id/tasks/:taskId/ad-fit',
  TASK_PRE_PUBLISH: '/projects/:id/tasks/:taskId/pre-publish-check',
  TASK_REPORTS: '/projects/:id/tasks/:taskId/reports',
  REPORT_PREVIEW: '/projects/:id/tasks/:taskId/reports/:reportId',
  MULTI_COMPARE: '/projects/:id/compare',
  COLLABORATE: '/projects/:id/collaborate',
  EXPORT_CENTER: '/export-center',
  SETTINGS: '/settings',
  SHARE: '/share/:token',
  ADMIN: '/admin',
} as const;
